import type { FeedItem, /* User, for future usage*/ Paper } from '@/types'

// ============================================================
// Mock feed data — replace with API calls later.
// Covers ALL academic disciplines, not just IT.
// ============================================================

// const mockUsers: User[] = [
//   {
//     id: 'u1',
//     username: 'mhaku_manalili',
//     email: 'mhaku.manalili@up.edu.ph',
//     first_name: 'Mhaku',
//     last_name: 'Manalili',
//     avatar_url: undefined,
//     reputation: 3200,
//     badges: [],
//     institution_id: 'inst_1',
//     department_id: 'dept_cs',
//     degree_level: 'undergraduate',
//     role: 'student',
//     is_verified: true,
//     is_verified_student: true,
//     papers_count: 4,
//     bookmarks_count: 31,
//     created_at: '2025-06-15T08:00:00Z',
//     updated_at: '2026-05-10T10:30:00Z',
//   },
//   {
//     id: 'u2',
//     username: 'alwina_bersales',
//     email: 'alwina.bersales@up.edu.ph',
//     first_name: 'Alwina',
//     last_name: 'Bersales',
//     avatar_url: undefined,
//     reputation: 2870,
//     badges: [],
//     institution_id: 'inst_1',
//     department_id: 'dept_natsci',
//     degree_level: 'masteral',
//     role: 'student',
//     is_verified: true,
//     is_verified_student: true,
//     papers_count: 3,
//     bookmarks_count: 28,
//     created_at: '2025-03-22T14:00:00Z',
//     updated_at: '2026-05-09T09:15:00Z',
//   },
//   {
//     id: 'u3',
//     username: 'tito_bobots',
//     email: 'tito.bobots@dlsu.edu.ph',
//     first_name: 'tito',
//     last_name: 'Bobots',
//     avatar_url: undefined,
//     reputation: 560,
//     badges: [],
//     institution_id: 'inst_2',
//     department_id: 'dept_eng',
//     degree_level: 'undergraduate',
//     role: 'student',
//     is_verified: true,
//     is_verified_student: true,
//     papers_count: 1,
//     bookmarks_count: 5,
//     created_at: '2025-11-05T07:30:00Z',
//     updated_at: '2026-04-28T13:00:00Z',
//   },
//   {
//     id: 'u4',
//     username: 'boy_bayani',
//     email: 'boy.bayani@pup.edu.ph',
//     first_name: 'Boy',
//     last_name: 'Bayani',
//     avatar_url: undefined,
//     reputation: 1100,
//     badges: [],
//     institution_id: 'inst_5',
//     department_id: 'dept_bus',
//     degree_level: 'undergraduate',
//     role: 'student',
//     is_verified: true,
//     is_verified_student: true,
//     papers_count: 2,
//     bookmarks_count: 14,
//     created_at: '2025-09-10T11:00:00Z',
//     updated_at: '2026-05-01T16:45:00Z',
//   },
//   {
//     id: 'u5',
//     username: 'dr_lakandiwa',
//     email: 'lakandiwa.santos@ust.edu.ph',
//     first_name: 'Dr. Lakandiwa',
//     last_name: 'Santos',
//     avatar_url: undefined,
//     reputation: 8400,
//     badges: [],
//     institution_id: 'inst_4',
//     department_id: 'dept_health',
//     degree_level: 'doctoral',
//     role: 'faculty',
//     is_verified: true,
//     is_verified_student: false,
//     papers_count: 15,
//     bookmarks_count: 203,
//     created_at: '2024-01-20T09:00:00Z',
//     updated_at: '2026-05-10T08:00:00Z',
//   },
//   {
//     id: 'u6',
//     username: 'prinsesa_mae',
//     email: 'prinsesa.mae@adamson.edu.ph',
//     first_name: 'Prinsesa Mae',
//     last_name: 'Dimaculangan',
//     avatar_url: undefined,
//     reputation: 920,
//     badges: [],
//     institution_id: 'inst_9',
//     department_id: 'dept_edu',
//     degree_level: 'undergraduate',
//     role: 'student',
//     is_verified: true,
//     is_verified_student: true,
//     papers_count: 1,
//     bookmarks_count: 11,
//     created_at: '2025-08-18T10:00:00Z',
//     updated_at: '2026-04-25T14:30:00Z',
//   },
//   {
//     id: 'u7',
//     username: 'kuya_jekjek',
//     email: 'jekjek.luna@mapua.edu.ph',
//     first_name: 'Jekjek',
//     last_name: 'Luna',
//     avatar_url: undefined,
//     reputation: 1950,
//     badges: [],
//     institution_id: 'inst_6',
//     department_id: 'dept_cs',
//     degree_level: 'undergraduate',
//     role: 'student',
//     is_verified: true,
//     is_verified_student: true,
//     papers_count: 2,
//     bookmarks_count: 19,
//     created_at: '2025-07-01T08:00:00Z',
//     updated_at: '2026-05-05T11:00:00Z',
//   },
//   {
//     id: 'u8',
//     username: 'doro_de_la_cruz',
//     email: 'doro.delacruz@feu.edu.ph',
//     first_name: 'Doro',
//     last_name: 'De La Cruz',
//     avatar_url: undefined,
//     reputation: 680,
//     badges: [],
//     institution_id: 'inst_8',
//     department_id: 'dept_arts',
//     degree_level: 'undergraduate',
//     role: 'student',
//     is_verified: true,
//     is_verified_student: true,
//     papers_count: 1,
//     bookmarks_count: 8,
//     created_at: '2026-01-12T09:00:00Z',
//     updated_at: '2026-05-08T16:00:00Z',
//   },
// ]

const mockPapers: Paper[] = [
  {
    id: 'p1',
    title: 'Development of a Low-Cost IoT-Based Water Quality Monitoring System for Taal Lake',
    abstract: 'This study aims to develop an affordable, real-time water quality monitoring system utilizing Internet of Things (IoT) sensors deployed across multiple stations in Taal Lake. The system measures pH, dissolved oxygen, turbidity, and temperature levels, transmitting data to a web-based dashboard for analysis by local environmental agencies and fishing communities. Results show 94.2% accuracy compared to laboratory-based testing methods, demonstrating viability for large-scale deployment in Philippine freshwater bodies.',
    authors: [
      { user_id: 'u1', name: 'Mhaku Manalili', avatar_url: undefined, is_primary: true },
    ],
    institution_id: 'inst_1',
    department_id: 'dept_cs',
    degree_level: 'undergraduate',
    paper_type: 'capstone',
    research_field: 'information_technology',
    methodology: 'design_and_development',
    year: 2026,
    keywords: ['IoT', 'water quality', 'Taal Lake', 'sensors', 'monitoring system'],
    file_url: '#',
    file_size: 4520000,
    page_count: 87,
    cover_image_url: undefined,
    license: 'cc_by_nc',
    status: 'approved',
    vote_score: 142,
    vote_count: 198,
    comment_count: 23,
    view_count: 1840,
    download_count: 312,
    bookmarks_count: 89,
    created_at: '2026-03-15T10:00:00Z',
    updated_at: '2026-05-09T14:30:00Z',
    published_at: '2026-03-20T08:00:00Z',
  },
  {
    id: 'p2',
    title: 'Antimicrobial Resistance Patterns of Escherichia coli in Selected River Systems of Cebu Province',
    abstract: 'This research paper examines the prevalence and antibiotic resistance profiles of Escherichia coli isolates collected from five major river systems in Cebu Province. Through microbiological culture, disk diffusion assays, and polymerase chain reaction (PCR) detection of resistance genes, the study identifies alarming multi-drug resistance rates of 67.3% against commonly prescribed antibiotics including ampicillin, tetracycline, and ciprofloxacin. The findings highlight the critical role of untreated agricultural runoff and inadequate wastewater management in accelerating antimicrobial resistance dissemination in Philippine waterways.',
    authors: [
      { user_id: 'u2', name: 'Alwina Bersales', avatar_url: undefined, is_primary: true },
    ],
    institution_id: 'inst_1',
    department_id: 'dept_natsci',
    degree_level: 'masteral',
    paper_type: 'research_paper',
    research_field: 'health_sciences',
    methodology: 'quantitative',
    year: 2026,
    keywords: ['antimicrobial resistance', 'E. coli', 'Cebu rivers', 'water pollution', 'public health'],
    file_url: '#',
    file_size: 12400000,
    page_count: 45,
    cover_image_url: undefined,
    license: 'cc_by',
    status: 'approved',
    vote_score: 184,
    vote_count: 210,
    comment_count: 32,
    view_count: 3800,
    download_count: 567,
    bookmarks_count: 312,
    created_at: '2026-01-08T13:00:00Z',
    updated_at: '2026-05-09T16:00:00Z',
    published_at: '2026-01-15T08:00:00Z',
  },
  {
    id: 'p3',
    title: 'Seismic Performance Evaluation of Bamboo-Reinforced Concrete Frame Structures',
    abstract: 'This research investigates the structural integrity and seismic resilience of concrete frame structures reinforced with treated bamboo as an alternative to conventional steel reinforcement. Through experimental testing and finite element analysis, the study compares load-bearing capacity, ductility, and crack propagation patterns between bamboo-reinforced and steel-reinforced specimens under simulated earthquake loading conditions per NSCP 2015 standards. Findings indicate that properly treated bamboo reinforcement achieves 78% of the performance metrics of steel reinforcement at 35% of the material cost.',
    authors: [
      { user_id: 'u3', name: 'tito Bobots', avatar_url: undefined, is_primary: true },
    ],
    institution_id: 'inst_2',
    department_id: 'dept_eng',
    degree_level: 'undergraduate',
    paper_type: 'thesis',
    research_field: 'architecture_and_engineering',
    methodology: 'experimental',
    year: 2026,
    keywords: ['bamboo reinforcement', 'seismic', 'concrete frames', 'NSCP', 'sustainable construction'],
    file_url: '#',
    file_size: 8900000,
    page_count: 156,
    cover_image_url: undefined,
    license: 'cc_by_nc_sa',
    status: 'approved',
    vote_score: 98,
    vote_count: 134,
    comment_count: 15,
    view_count: 2340,
    download_count: 456,
    bookmarks_count: 201,
    created_at: '2026-02-10T09:00:00Z',
    updated_at: '2026-05-07T11:20:00Z',
    published_at: '2026-02-18T08:00:00Z',
  },
  {
    id: 'p4',
    title: 'Feasibility of Micro-Franchise Sari-Sari Store Digitalization in Metro Manila Low-Income Communities',
    abstract: 'This feasibility study evaluates the economic viability of implementing a micro-franchise digital platform for sari-sari store operators in low-income communities across Metro Manila. Using a mixed-methods approach combining surveys from 450 store operators in Quezon City, Manila, and Caloocan with financial modeling and market analysis, the study assesses digital inventory management, mobile payment integration, and supplier chain optimization. Results project a 32% increase in average monthly net income for participating stores within the first year of platform adoption, with a break-even period of 18 months for the franchise operation.',
    authors: [
      { user_id: 'u4', name: 'Boy Bayani', avatar_url: undefined, is_primary: true },
    ],
    institution_id: 'inst_5',
    department_id: 'dept_bus',
    degree_level: 'undergraduate',
    paper_type: 'feasibility_study',
    research_field: 'business_and_management',
    methodology: 'mixed_method',
    year: 2026,
    keywords: ['micro-franchise', 'sari-sari store', 'digitalization', 'Metro Manila', 'feasibility'],
    file_url: '#',
    file_size: 6780000,
    page_count: 124,
    cover_image_url: undefined,
    license: 'cc_by_nc_nd',
    status: 'approved',
    vote_score: 76,
    vote_count: 102,
    comment_count: 18,
    view_count: 1560,
    download_count: 234,
    bookmarks_count: 67,
    created_at: '2026-04-20T11:00:00Z',
    updated_at: '2026-05-10T15:00:00Z',
    published_at: '2026-04-25T08:00:00Z',
  },
  {
    id: 'p5',
    title: 'Lived Experiences of DepEd Public School Teachers Implementing Modular Distance Learning During Post-Pandemic Recovery',
    abstract: 'This qualitative study explores the lived experiences of 15 Department of Education (DepEd) public school teachers across three divisions in Region IV-A who continued implementing modular distance learning modalities during the 2024-2025 post-pandemic recovery period. Through in-depth semi-structured interviews and thematic analysis, the study identifies five major themes: resource inadequacy, assessment authenticity challenges, student engagement barriers, parental involvement dynamics, and professional resilience. The findings provide evidence-based recommendations for DepEd policy makers on sustainable hybrid learning frameworks that address the persistent digital divide in Philippine public education.',
    authors: [
      { user_id: 'u6', name: 'Prinsesa Mae Dimaculangan', avatar_url: undefined, is_primary: true },
    ],
    institution_id: 'inst_9',
    department_id: 'dept_edu',
    degree_level: 'undergraduate',
    paper_type: 'research_paper',
    research_field: 'education',
    methodology: 'qualitative',
    year: 2026,
    keywords: ['modular distance learning', 'DepEd', 'post-pandemic', 'teacher experiences', 'qualitative'],
    file_url: '#',
    file_size: 4200000,
    page_count: 134,
    cover_image_url: undefined,
    license: 'cc_by_nc',
    status: 'approved',
    vote_score: 119,
    vote_count: 156,
    comment_count: 22,
    view_count: 2100,
    download_count: 298,
    bookmarks_count: 156,
    created_at: '2026-04-05T08:00:00Z',
    updated_at: '2026-05-10T10:00:00Z',
    published_at: '2026-04-12T08:00:00Z',
  },
  {
    id: 'p6',
    title: 'Design and Development of a Solar-Powered Cold Storage System for Small-Scale Fishermen in Zambales',
    abstract: 'This capstone project presents the design, prototyping, and field testing of a modular solar-powered cold storage unit tailored for small-scale fishing communities in Zambales. The system utilizes photovoltaic panels coupled with a high-efficiency DC compressor and phase-change material thermal storage to maintain fish storage temperatures of -2 to 2 degrees Celsius without grid dependency. Field testing over 90 days across three coastal barangays demonstrates a post-harvest loss reduction from 28% to 6%, with a projected return on investment period of 2.3 years through cooperative cost-sharing models.',
    authors: [
      { user_id: 'u7', name: 'Jekjek Luna', avatar_url: undefined, is_primary: true },
    ],
    institution_id: 'inst_6',
    department_id: 'dept_cs',
    degree_level: 'undergraduate',
    paper_type: 'capstone',
    research_field: 'agriculture_and_fisheries',
    methodology: 'design_and_development',
    year: 2025,
    keywords: ['solar power', 'cold storage', 'fishermen', 'Zambales', 'post-harvest loss'],
    file_url: '#',
    file_size: 18700000,
    page_count: 178,
    cover_image_url: undefined,
    license: 'cc_by_nc',
    status: 'approved',
    vote_score: 203,
    vote_count: 245,
    comment_count: 35,
    view_count: 4100,
    download_count: 623,
    bookmarks_count: 345,
    created_at: '2025-07-22T09:00:00Z',
    updated_at: '2026-05-08T14:00:00Z',
    published_at: '2025-08-01T08:00:00Z',
  },
  {
    id: 'p7',
    title: 'Adaptive Reuse of Heritage Structures in Intramuros: A Sustainable Urban Renewal Framework',
    abstract: 'This capstone project proposes a comprehensive architectural framework for the adaptive reuse of deteriorating heritage structures within the Intramuros district of Manila. The study employs qualitative case analysis of three priority structures — Baluarte de San Diego, Aduana Building, and the Beaterio de Santa Catalina — combining heritage conservation principles with modern structural engineering requirements and commercial viability assessments. The resulting framework provides a phased implementation plan that preserves historical integrity while creating functional community spaces for education, cultural tourism, and small enterprise.',
    authors: [
      { user_id: 'u8', name: 'Doro De La Cruz', avatar_url: undefined, is_primary: true },
    ],
    institution_id: 'inst_8',
    department_id: 'dept_arts',
    degree_level: 'undergraduate',
    paper_type: 'capstone',
    research_field: 'architecture_and_engineering',
    methodology: 'case_study',
    year: 2025,
    keywords: ['adaptive reuse', 'heritage conservation', 'Intramuros', 'sustainable architecture', 'urban renewal'],
    file_url: '#',
    file_size: 34500000,
    page_count: 210,
    cover_image_url: undefined,
    license: 'cc_by',
    status: 'approved',
    vote_score: 231,
    vote_count: 278,
    comment_count: 41,
    view_count: 5200,
    download_count: 789,
    bookmarks_count: 423,
    created_at: '2025-10-05T07:00:00Z',
    updated_at: '2026-05-10T09:00:00Z',
    published_at: '2025-10-12T08:00:00Z',
  },
  {
    id: 'p8',
    title: 'Kuwentong Karanasan ng Single Mothers sa Pag-Arise ng Online Negosyo sa Pamayanan ng Cavite',
    abstract: 'This qualitative study documents the lived experiences and entrepreneurial journeys of 12 single mothers from low-income barangays in Cavite who established online micro-businesses during and after the COVID-19 pandemic. Using phenomenological methodology and in-depth narrative interviews, the research explores themes of financial independence, digital literacy acquisition, work-life balance challenges, and community support systems. The study reveals that social media-based micro-enterprises served not only as economic lifelines but also as platforms for personal empowerment and community leadership among participants, with average monthly incomes increasing by 285% from pre-pandemic levels.',
    authors: [
      { user_id: 'u1', name: 'Mhaku Manalili', avatar_url: undefined, is_primary: true },
    ],
    institution_id: 'inst_1',
    department_id: 'dept_ssci',
    degree_level: 'undergraduate',
    paper_type: 'research_paper',
    research_field: 'social_sciences',
    methodology: 'qualitative',
    year: 2025,
    keywords: ['single mothers', 'online business', 'Cavite', 'empowerment', 'pandemic recovery'],
    file_url: '#',
    file_size: 5100000,
    page_count: 92,
    cover_image_url: undefined,
    license: 'cc_by_nc_sa',
    status: 'approved',
    vote_score: 167,
    vote_count: 203,
    comment_count: 29,
    view_count: 3400,
    download_count: 478,
    bookmarks_count: 234,
    created_at: '2025-11-18T10:00:00Z',
    updated_at: '2026-05-09T12:00:00Z',
    published_at: '2025-11-25T08:00:00Z',
  },
]

export const feedItems: FeedItem[] = mockPapers.map((paper) => ({
  paper,
  user_vote: null,
  is_bookmarked: false,
}))

export const institutionNames: Record<string, string> = {
  inst_1: 'University of the Philippines',
  inst_2: 'De La Salle University',
  inst_3: 'Ateneo de Manila University',
  inst_4: 'University of Santo Tomas',
  inst_5: 'Polytechnic University of the Philippines',
  inst_6: 'Mapua University',
  inst_7: 'University of the East',
  inst_8: 'Far Eastern University',
  inst_9: 'Adamson University',
  inst_10: 'University of San Carlos',
  inst_11: 'Silliman University',
  inst_12: 'Xavier University',
  inst_other: 'Other',
}

export const departmentNames: Record<string, string> = {
  dept_cs: 'College of Computer Studies',
  dept_eng: 'College of Engineering',
  dept_bus: 'College of Business & Accountancy',
  dept_arts: 'College of Arts & Sciences',
  dept_edu: 'College of Education',
  dept_health: 'College of Health Sciences',
  dept_archi: 'College of Architecture & Design',
  dept_law: 'College of Law',
  dept_crim: 'College of Criminal Justice',
  dept_maritime: 'College of Maritime Education',
  dept_agri: 'College of Agriculture & Fisheries',
  dept_hosp: 'College of Hospitality & Tourism',
  dept_comms: 'College of Communication & Media',
  dept_math: 'College of Mathematics & Statistics',
  dept_ssci: 'College of Social Sciences',
  dept_natsci: 'College of Natural Sciences',
}